filebeat.inputs:
  - type: log
    enabled: true
    paths: [/logs/test.log]
    scan_frequency: 500ms

output.logstash:
  hosts: ["fluent-bit:5044"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/certs/ca.crt"]

logging.level: info
logging.to_stderr: true
