[SERVICE]
    Flush        1
    Log_Level    info
    Plugins_File /fluent-bit/etc/plugins.conf

[INPUT]
    Name         beats
    Tag          beats.*
    address      0.0.0.0:5044
    enable_v2    true
    tls_active   true
    cert_file    /certs/server.crt
    key_file     /certs/server.key
    ca_file      /certs/ca.crt

[OUTPUT]
    Name   stdout
    Match  *
